/*
===========================================
Retail Sales Analytics using SQL
Business Queries

Database: SQLite

This file contains SQL queries written to
answer real-world business questions using
the Retail Sales dataset.
===========================================
*/

-- ============================================================
-- Business Requirement 1
-- Display customer name, product name, quantity ordered,
-- and order status for every order.
-- ============================================================

SELECT
    customers.customer_name,
    products.product_name,
    orders.quantity,
    orders.order_status
FROM orders
INNER JOIN customers
    ON orders.customer_id = customers.customer_id
INNER JOIN products
    ON orders.product_id = products.product_id;


-- ============================================================
-- Business Requirement 2
-- Calculate revenue generated by each completed order.
-- Revenue = Price × Quantity
-- ============================================================

SELECT
    orders.order_id,
    products.product_name,
    orders.quantity,
    (products.price * orders.quantity) AS Revenue
FROM orders
INNER JOIN products
    ON orders.product_id = products.product_id
WHERE orders.order_status = 'Completed';


-- ============================================================
-- Business Requirement 3
-- Find total revenue generated by each customer.
-- Display results in descending order of revenue.
-- ============================================================

SELECT
    customers.customer_name,
    SUM(products.price * orders.quantity) AS Revenue
FROM orders
INNER JOIN customers
    ON orders.customer_id = customers.customer_id
INNER JOIN products
    ON orders.product_id = products.product_id
WHERE orders.order_status = 'Completed'
GROUP BY customers.customer_name
ORDER BY Revenue DESC;


-- ============================================================
-- Business Requirement 4
-- Calculate city-wise completed-order revenue.
-- Display cities in descending order of revenue.
-- ============================================================

SELECT
    customers.city,
    SUM(products.price * orders.quantity) AS Revenue
FROM orders
INNER JOIN customers
    ON orders.customer_id = customers.customer_id
INNER JOIN products
    ON orders.product_id = products.product_id
WHERE orders.order_status = 'Completed'
GROUP BY customers.city
ORDER BY Revenue DESC;


-- ============================================================
-- Business Requirement 5
-- Find customers who have never placed an order.
-- ============================================================

SELECT
    customers.customer_name
FROM customers
LEFT JOIN orders
    ON customers.customer_id = orders.customer_id
WHERE orders.order_id IS NULL;


-- ============================================================
-- Business Requirement 6
-- Categorize products based on price.
--
-- Premium : Price >= 30000
-- Standard: Price >= 5000
-- Budget  : Price < 5000
-- ============================================================

SELECT
    product_name,
    price,
    CASE
        WHEN price >= 30000 THEN 'Premium'
        WHEN price >= 5000 THEN 'Standard'
        ELSE 'Budget'
    END AS Product_Level
FROM products;


-- ============================================================
-- Business Requirement 7
-- Find completed orders whose revenue is greater
-- than the average completed-order revenue.
-- ============================================================

SELECT
    orders.order_id,
    products.product_name,
    (products.price * orders.quantity) AS Revenue
FROM orders
INNER JOIN products
    ON orders.product_id = products.product_id
WHERE orders.order_status = 'Completed'
AND (products.price * orders.quantity) >
(
    SELECT
        AVG(products.price * orders.quantity)
    FROM orders
    INNER JOIN products
        ON orders.product_id = products.product_id
    WHERE orders.order_status = 'Completed'
);


-- ============================================================
-- Business Requirement 8
-- Find products that have never been ordered.
--
-- Cancelled orders are also considered as orders.
-- ============================================================

SELECT
    products.product_name
FROM products
LEFT JOIN orders
    ON products.product_id = orders.product_id
WHERE orders.order_id IS NULL;


/*
===========================================================
End of Business Queries
===========================================================
*/
